// LOCALHOST ### Get all course GET http://localhost:8080/course

### Get contact by id GET http://localhost:8080/course/[id]

### Create contact POST http://localhost:8080/course HTTP/1.1 content-type: application/json

{
    "firstName":"Dam", 
    "lastName":"Wise", 
    "email":"dWiser@test.com", 
    "favoriteColor":"Red", 
    "birthday":"12/1/2000"
}

### PUT contact PUT http://localhost:8080/course/[id] HTTP/1.1 content-type: application/json

{
    "firstName":"Sarah", 
    "lastName":"Birch", 
    "email":"test@gmail.com", 
    "favoriteColor":"Green", 
    "birthday":"12/12/20"
} ### DELETE contact DELETE http://localhost:8080/course/[id] HTTP/1.1

// PRODUCTION Deploy ### Get all course GET https://cit341ovalle.herokuapp.com/course
### Get contact by id GET https://cit341ovalle.herokuapp.com/course/[id]

### Create contact POST https://cit341ovalle.herokuapp.com/course HTTP/1.1 content-type: application/json

{
    "firstName":"Dam", 
    "lastName":"Wise", 
    "email":"dWiser@test.com", 
    "favoriteColor":"Red", 
    "birthday":"12/1/2000"
}

### PUT contact PUT https://cit341ovalle.herokuapp.com/course/[id] HTTP/1.1 content-type: application/json

{
    "firstName":"Sarah", 
    "lastName":"Birch", 
    "email":"sarahB@gmail.com", 
    "favoriteColor":"Yellow", 
    "birthday":"06/12/20"
}

### DELETE contact DELETE https://cit341ovalle.herokuapp.com/course/[id] HTTP/1.1